### ISSUE TITLE
front end homework difficulty 

### ISSUE THREAD

**Issue by hanford** [eaze/homework-front-end#2]
So, I think there is a consensus on the difficulty of this project being too easy. 

I've built tools on top of githubs API before, [angular + ionic + cordova](https://github.com/hanford/Mobile-Github-Client)  ... 

One thing that kind of through me off (though I was admittedly junior) was repo navigation. Basically you need to account for N deep files nested in folders recursively. 

Maybe we could incorporate a project view in the homework? I feel like a public github viewer is almost cliche at this point

Thoughts? @ghigo @nickick @klaymon @Techwraith

**Comment by Techwraith** [comment]
I really like that we start simple with the homework and ramp up the
difficulty in the in person coding session. Whatever we do, we should make
sure that we leave some things open for candidates to implement in person
with us.

**Comment by hanford** [comment]
Pagination and filtering are also quite easy. Perhaps we should go down the path of implementing the recursion step above ¯\_(ツ)_/¯
